### ISSUE TITLE
Please declare a license

### ISSUE THREAD

**Issue by mpenning** [FliesLikeABrick/orphanreaper#1]
Technically, nobody should use this code without an explicit license...

Quoting [a software licensing article](https://www.contractscounsel.com/t/us/software-license#toc--why-software-licensing-is-important-):
> Before any software can be installed, it has to be legally licensed. Otherwise, it would be considered a breach of copyright law to use the software.

**Comment by FliesLikeABrick** [comment]
Thanks for the guidance @mpenning  I am adding a license now

**Comment by FliesLikeABrick** [comment]
LICENSE has been added (GPLv3)
